import React from "react";

import Head from "next/head";
import { Box, Card, Typography } from "@mui/material";

import { AuthContext } from "../src/context/authContext";
import { useRouter } from "next/router";
import { useGetUserByIdQuery } from "../src/store/services/api";
import Loader from "../src/components/loader";
import { useSelector } from "react-redux";
import { RootState } from "../src/store/store";

export default function Home() {
  const router = useRouter();
  const { currentUser } = React.useContext(AuthContext);
  const token = useSelector<RootState>((state) => state.auth.token);
  const {
    data: user,
    isError,
    isLoading,
  } = useGetUserByIdQuery({
    id: currentUser?.uid as string,
  });

  React.useEffect(() => {
    token ? router.push("/") : router.push("/login");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser]);

  if (isError || isLoading || !user) {
    return <Loader />;
  }

  return (
    <>
      <Head>
        <title>CRM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <main>
        <Box
          sx={{
            backgroundColor: "#4f4e4b",
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            position: "absolute",
            height: "100%",
            width: "100%",
          }}
        >
          <Box
            sx={{ margin: "auto", padding: "10% 35% 10% 15%", color: "white" }}
          >
            <Box sx={{ fontSize: { xs: "36px", md: "76px" } }}>
              Welcome,
              <span style={{ color: "brown" }}>{user.name}</span>
            </Box>

            <Box sx={{ fontSize: "36px" }}>
              This is the Content Management System and here's some content. You
              role is <span style={{ color: "brown" }}>{user.role}</span> and
              email is{" "}
              <span style={{ color: "brown" }}>{currentUser?.email}</span>
            </Box>
            <br />
          </Box>
        </Box>
      </main>
    </>
  );
}
